sudo: required
language: c
branches:
    except:
        - packaging

before_install:
    - sudo apt-get update
install:
    - sudo apt-get install gcc-avr binutils-avr avr-libc valgrind pastebinit cppcheck
    - pip install --user cpp-coveralls
script:
    - make -f makefile-avr MCU=atmega328p
    - make -f makefile-avr clean
    - make all
    - ./genconf.sh --sres 256 --sreq 256 --mres 256 --mreq 256 --mdat 256
    - make -f makefile-coverage all
    - ./genconf.sh --sres 1 --sreq 1 --mres 1 --mreq 1 --mdat 1
    - make -f makefile-coverage all
    - ./genconf.sh -r
    - make conf
    - make -f makefile-coverage all
after_success:
    - coveralls --verbose --exclude test/test.c
    - find . -name "*.c" | xargs cppcheck > cppcheck.log
    - pastebinit -i cppcheck.log
    - pastebinit -i valgrind.xml
    - pastebinit -i massif.out
    - pastebinit -i coverage-test.log
    - tar -cvf liblightmodbus-travis.tar .
    - curl -F file="@liblightmodbus-travis.tar" https://filebin.ca/upload.php
